# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Intercept-Me
tagline:          'Security Professional'
description:      ' '
url:              http://Intercept-Me.github.io
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
